"""Alter hasil_naive_bayes column in PenilaianHafalan

Revision ID: 179c911b7b62
Revises: 7ec29af99622
Create Date: 2025-07-26 06:56:57.615221

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '179c911b7b62'
down_revision = '7ec29af99622'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('PenilaianHafalan', 'hasil_naive_bayes', existing_type=sa.String(length=50), nullable=False, existing_nullable=True, server_default='Belum Diprediksi') # Menghapus ON UPDATE CURRENT_TIMESTAMP
    # Untuk baris yang sudah ada, setel nilai default jika null
    op.execute("UPDATE PenilaianHafalan SET hasil_naive_bayes = 'Belum Diprediksi' WHERE hasil_naive_bayes IS NULL")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('PenilaianHafalan', 'hasil_naive_bayes', existing_type=sa.String(length=50), nullable=True, existing_nullable=False, server_default=None)
    # ### end Alembic commands ###
