"""Add profile_picture column

Revision ID: 67d885446952
Revises: b1bd033739d1
Create Date: 2025-07-12 10:22:38.120194

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '67d885446952'
down_revision = 'b1bd033739d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Admin', sa.Column('profile_picture', sa.String(length=255), nullable=True))
    op.add_column('Guru', sa.Column('profile_picture', sa.String(length=255), nullable=True))
    op.add_column('Santri', sa.Column('profile_picture', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Santri', 'profile_picture')
    op.drop_column('Guru', 'profile_picture')
    op.drop_column('Admin', 'profile_picture')
    # ### end Alembic commands ###
