"""Add kelancaran, kefasihan, and hasil_naive_bayes columns to PenilaianHafalan table

Revision ID: 7ec29af99622
Revises: fb677578c964
Create Date: 2025-07-26 06:44:00.204539

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ec29af99622'
down_revision = 'fb677578c964'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('PenilaianHafalan', sa.Column('kelancaran', sa.Integer(), nullable=False))
    op.add_column('PenilaianHafalan', sa.Column('kefasihan', sa.Integer(), nullable=False))
    op.add_column('PenilaianHafalan', sa.Column('hasil_naive_bayes', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('PenilaianHafalan', 'hasil_naive_bayes')
    op.drop_column('PenilaianHafalan', 'kefasihan')
    op.drop_column('PenilaianHafalan', 'kelancaran')
    # ### end Alembic commands ###
