"""Add PredictionResult table

Revision ID: d5bfe1269372
Revises: 67d885446952
Create Date: 2025-07-12 10:51:20.853255

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd5bfe1269372'
down_revision = '67d885446952'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Admin',
    sa.Column('admin_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('nama_lengkap', sa.String(length=100), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('profile_picture', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('admin_id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('Guru',
    sa.Column('guru_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nama_lengkap', sa.String(length=100), nullable=False),
    sa.Column('nip', sa.String(length=20), nullable=False),
    sa.Column('pendidikan_terakhir', sa.String(length=50), nullable=True),
    sa.Column('nomor_telepon', sa.String(length=15), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('profile_picture', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('guru_id'),
    sa.UniqueConstraint('nip')
    )
    op.create_table('Santri',
    sa.Column('santri_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nama_lengkap', sa.String(length=100), nullable=False),
    sa.Column('nis', sa.String(length=20), nullable=False),
    sa.Column('kelas', sa.String(length=50), nullable=False),
    sa.Column('alamat', sa.Text(), nullable=True),
    sa.Column('nama_orang_tua', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('profile_picture', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('santri_id'),
    sa.UniqueConstraint('nis')
    )
    op.create_table('PredictionResult',
    sa.Column('prediction_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('santri_id', sa.Integer(), nullable=False),
    sa.Column('tingkat_hafalan', sa.String(length=50), nullable=False),
    sa.Column('jumlah_setoran', sa.Integer(), nullable=False),
    sa.Column('kehadiran', sa.Integer(), nullable=False),
    sa.Column('hasil_prediksi', sa.String(length=50), nullable=False),
    sa.Column('predicted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['santri_id'], ['Santri.santri_id'], ),
    sa.PrimaryKeyConstraint('prediction_id')
    )
    with op.batch_alter_table('guru', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('nip'))

    op.drop_table('guru')
    with op.batch_alter_table('santri', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('nis'))

    op.drop_table('santri')
    with op.batch_alter_table('admin', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('username'))

    op.drop_table('admin')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin',
    sa.Column('admin_id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('username', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('password_hash', mysql.VARCHAR(length=128), nullable=False),
    sa.Column('nama_lengkap', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('last_login', mysql.DATETIME(), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.Column('profile_picture', mysql.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('admin_id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('admin', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('username'), ['username'], unique=True)

    op.create_table('santri',
    sa.Column('santri_id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('nama_lengkap', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('nis', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('kelas', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('alamat', mysql.TEXT(), nullable=True),
    sa.Column('nama_orang_tua', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('password_hash', mysql.VARCHAR(length=128), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.Column('profile_picture', mysql.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('santri_id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('santri', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('nis'), ['nis'], unique=True)

    op.create_table('guru',
    sa.Column('guru_id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('nama_lengkap', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('nip', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('pendidikan_terakhir', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('nomor_telepon', mysql.VARCHAR(length=15), nullable=True),
    sa.Column('password_hash', mysql.VARCHAR(length=128), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.Column('profile_picture', mysql.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('guru_id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('guru', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('nip'), ['nip'], unique=True)

    op.drop_table('PredictionResult')
    op.drop_table('Santri')
    op.drop_table('Guru')
    op.drop_table('Admin')
    # ### end Alembic commands ###
